### ISSUE TITLE
Support for runtime options

### ISSUE THREAD

**Issue by alberto-bottarini** [guratr/nova-command-runner#5]
You could use standard nova action fields to allow command with runtime options

**Comment by srinathreddydudi** [comment]
Hey @alberto-bottarini 
If you are still looking for a fix for this, I released an updated version based on this package. Please check https://github.com/binarybuilds/nova-advanced-command-runner

@guratr I felt like this package is not actively maintained. So i created a separate package based on this and added proper credits to this package.

**Comment by alberto-bottarini** [comment]
Thanks. I will take a look
