### ISSUE TITLE
Problem with SSL

### ISSUE THREAD

**Issue by Muetze42** [guratr/nova-command-runner#6]
```
Mixed Content: The page at 'https://daysndaze.net/backend/command-runner' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://daysndaze.net/nova-vendor/guratr/command-runner/history'. This request has been blocked; the content must be served over HTTPS.
```

My domain runs over cloudflare, with cloudflare free certificate.

**Comment by srinathreddydudi** [comment]
Hey @NormanHuth 
If you are still looking for a fix for this, I released an updated version based on this package. Please check https://github.com/binarybuilds/nova-advanced-command-runner

@guratr I felt like this package is not actively maintained. So i created a separate package based on this and added proper credits to this package.

**Comment by Muetze42** [comment]
That's actually already over. I have the commands now only for developers. And apart from that, I've included actions.
